# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18thyLBqh0m1s5kBSUC_gdwHOIuk6Zciv
"""

n1=int(input())
n2=int(input())
if n1>n2:
  print("n1 is largest")
else:
  print("n2 is largest")



n=int(input())
if(n>0):
  print("Positive number")
elif(n<0):
  print("Negative number")
else:
  print("Zero")

y=int(input())
if(y%400==0):
  print("Leap year")
elif(y%4==0 and y%100!=0):
  print("Leap year")
else:
  print("Not leap year")

n=int(input())
if(n%2==0):
  print("Even")
else:
  print("Odd")

n=int(input())
fact=1
for i in range(1,n+1):
    fact=fact*i
print(fact)

text=input()
rev=text[::-1]
if text==rev:
  print("Palindrome")
else:
  print("Not Palindrome")

word1=input()
word2=input()
if sorted(word1)==sorted(word2):
  print("anagram")
else:
  print("Not anagram")

for num in range(2,51):
  prime=True
  for i in range(2,num):
    if num%2==0:
      prime=False
  if prime:
    print(num)

temp=float(input())
fahrenheit=temp*(9/5)+32
print(fahrenheit)

fahrenheit=float(input())
celcious=5/9*(fahrenheit-32)
print(celcious)

#FIBONICII
a=0
b=1
n=int(input())
print(a)
print(b)
for i in range(n-2):
  c=a+b
  print(c)
  a=b
  b=c



a=int(input())
b=int(input())
print("Before swapping")
print("A=",a);print("B=",b)
print("After swapping")
a,b=b,a
print("A=",a);print("B=",b)

n1=float(input())
n2=float(input())
n3=float(input())
avg=(n1+n2+n3)/3
print(avg)



txt1=input()
txt2=input()
if sorted(txt1)==sorted(txt2):
  print("annagram")
else:
  print("not an annagram")

word=input()
vowels="aeiouAEIOU"
fv=[]
count=0
for letter in word:
  if letter in vowels:
    count+=1
    fv.append(letter)
print(fv)
print(count)

print("lakshman""\n""cse")

num1 = 36
num2 = 60
gcd = 1

for i in range(1, min(num1, num2)):
    if num1 % i == 0 and num2 % i == 0:
        gcd = i
print("GCD of", num1, "and", num2, "is", gcd)

from math import gcd

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

answer = gcd(num1, num2)

print("GCD is:", answer)

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

small = min(num1, num2)

gcd = 1

for i in range(1, small + 1):
    if num1 % i == 0 and num2 % i == 0:
        gcd = i

print("GCD is:", gcd)

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

big = max(num1, num2)

while True:
    if big % num1 == 0 and big % num2 == 0:
        print("LCM is:", big)
        break
    big = big + 1

lst=[3,27,29,7,65,92]
print(max(lst))

a=int(input("Enter the 1st number:"))
b=int(input("Enter the 2nd number:"))
strng=input()
if(strng=='+'):
  print(a+b)
elif(strng=='-'):
  print(a-b)
elif(strng=='*'):
  print(a*b)
elif(strng=='/'):
  print(a/b)
elif(strng=='%'):
  print(a%b)
else:
  print("Invalid operator")

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

for i in range(6,1,-1):
  for j in range(1,i):
    print("*",end=" ")
  print()

for i in range(5, 0, -1):
    for k in range(5 - i):
        print(" ", end=" ")
    for j in range(i):
        print("*", end=" ")

    print()



a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

largest = max(a, b, c)
print("The largest number is:", largest)

n=int(input())
if n>0 and (n & 4(n-1)==0):
  print("Power of 2")
else:
  print("Not a power of 2")

n=3
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "*(n-i)+"* "*i)

s1 = input("Enter first string: ")
s2 = input("Enter second string: ")

if len(s1) != len(s2):
    print("Not Anagram")
else:
    flag = True
    for ch in s1:
        if s1.count(ch) != s2.count(ch):
            flag = False
            break
    if flag:
        print("Anagram")
    else:
        print("Not Anagram")

s = input()
vowels = "aeiouAEIOU"
v = []
for ch in s:
    if ch in vowels:
        v.append(ch)
v.reverse()
result = ""
j = 0
for ch in s:
    if ch in vowels:
        result += v[j]
        j += 1
    else:
        result += ch
print(result)

inp=list(map(int,input().split()))
smallest=1
while smallest in inp:
  smallest+=1
print(smallest)

s = input()
longest = 0
for i in range(len(s)):
    temp = ""
    for j in range(i, len(s)):
        if s[j] not in temp:
            temp += s[j]
            longest = max(longest, len(temp))
        else:
            break
print(longest)

s = input()
longest = ""
for i in range(len(s)):
    for j in range(i, len(s)):
        sub = s[i:j+1]
        if sub == sub[::-1]:
            if len(sub) > len(longest):
                longest = sub
print(longest)

s1 = input()
s2 = input()

if len(s1) != len(s2):
    print("NO")
else:
    count = 0

    for i in range(len(s1)):
        if s1[i] != s2[i]:
            count += 1

    if count == 1:
        print("YES")
    else:
        print("NO")

n = int(input())

rev = 0
temp = n

while temp != 0:
    digit = temp % 10
    rev = rev * 10 + digit
    temp //= 10

count1 = 0
for i in range(1, n + 1):
    if n % i == 0:
        count1 += 1
count2 = 0
for i in range(1, rev + 1):
    if rev % i == 0:
        count2 += 1

if count1 == 2 and count2 == 2:
    print("Prime")
else:
    print("Not prime")

n1=int(input())
rev1=0
n1sq=n1**2
temp1=n1sq
while(temp1!=0):
    digit1=temp1%10
    rev1=rev1*10+digit1
    temp1=temp1//10
rev2=0
temp2=n1
while(temp2!=0):
    digit2=temp2%10
    rev2=rev2*10+digit2
    temp2=temp2//1
rev2sq=rev2**2
if(rev1==rev2sq):
    print("Adam number")
else:
    print("Not adam number")

n=int(input())
for i in range(1,n+1):
  if(i%2==0):
    print("-",i)
  else:
    print(i)

n=input()
a=n
b=n[1:]+n[0]
c=n[-1]+n[0]+n[1]
A=int(a)
B=int(b)
C=int(c)
count1=0
count2=0
count3=0
for i in range(1,A+1):
  if(A%i==0):
    count1+=1
for i in range(1,B+1):
  if(B%i==0):
    count2+=1
for i in range(1,C+1):
  if(C%i==0):
    count3+=1
if(count1==2 and count2==2 and count3==2):
  print("prime")
else:
  print("Not prime")